### ISSUE TITLE
Infografia-isaireyesp1 

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/infografia-isaireyesp1#2]
![Sistemas numericos](https://user-images.githubusercontent.com/80172078/133549757-8a4d6a9b-3820-450a-a834-188771251a59.png)

**Comment by Arlet04** [comment]
Redacción y ortografía (evidencia adecuada) contiene errores de acentuación  por lo que hay revisar bien la ortografía (2 puntos)
Exposición de ideas centrales (evidencia clara y precisa)  tiene buena síntesis ( 3 puntos )
organización de la información (evidencia clara y detallada) es breve la información y clara lo recomendable es no amontonar mucho texto ya que eso pierde el contraste de la presentación (2 puntos)
uso de imágenes y colores (evidencia clara y detallada) contiene suficientes imágenes y muy buena presentación (3 puntos)
presentación visual (alguna evidencia) contiene demasiada información por ello pierde el orden del trabajo presentado (2 puntos)
Referencias (poca evidencia) no emplea ninguna referencia (0 puntos)
Presentación (evidencia clara y detallada) realizó la entrega en tiempo y de forma adecuada (3)
Total: 15/21
calificación:14.28 % /20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Debe ser una infografía no un mapa mental

**Comment by isaireyesp1** [comment]
[SIstema numerico.pdf](https://github.com/SistemasTecTlaxiaco/infografia-isaireyesp1/files/7197544/SIstema.numerico.pdf)

**Comment by isaireyesp1** [comment]
[my-visual_55951838 (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-isaireyesp1/files/7210910/my-visual_55951838.1.pdf)

**Comment by isaireyesp1** [comment]
[sistemas numericos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-isaireyesp1/files/7210914/sistemas.numericos.pdf)

**Comment by isaireyesp1** [comment]
> Debe ser una infografía no un mapa mental

**Comment by Arlet04** [comment]
Redacción y ortografía (evidencia adecuada) Contiene textos en ingles por lo que impide entender un poco lo que se quiere dar a conocer(2 puntos)
Exposición de ideas centrales (evidencia clara y precisa) tiene buena síntesis (3 puntos) es breve la información y clara (3 puntos)
uso de imágenes y colores (evidencia clara y detallada) contiene suficientes imágenes y muy buena presentación (3 puntos)
presentación visual (evidencia clara y detallada) lo recomendable es poner el texto en español por lo que no es una materia de ingles (2 puntos)
Referencias (poca evidencia) no emplea ninguna referencia solo el documento en el que trabajo (1 punto)
Presentación (poca evidencia) por motivo de la devolución de la actividad y no acatar lo que se pedia la entrega se tomará como retrazada(1)
Total: 15/21
calificación: 14.28% / 20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado
